---
title: "Milestone 4"
author: "Pieter Quinton"
date: "10/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(scipen = 999)
library(tidyverse)
library(dplyr)
library(ggplot2)

dir.create("Graphics")
```

```{r data}
zillow_data <- read.csv("Metro_Zhvi_SingleFamilyResidence.csv")
```

```{r plot}

#I just made a simple ggplot with geom point to observe the relationship between population and median home value at one point in time. Logged the x axis because I thought that made the data easier to visualize because there were several cities with extremely high median home values. 

plot1 <- zillow_data %>%
  ggplot(aes(x=X2019.08, y=SizeRank)) +
    geom_point() +
    scale_x_log10() + 
    scale_y_reverse() +
    geom_smooth(method = "lm", se = FALSE) +
    labs(title = "Relationship Between Population and Median House Price",
         subtitle = "Data from the 805 largest cities in the United States as of July, 2019",
         x = "Median House Price ($)",
         y = "Population Ranked",
         caption = "As the plot shows, there is a positive relationship between population and median house price.\nThe scale on the y-axis has been flipped so the most populous cities are at the top and the least populous cities are at the bottom.") +
  theme(
    plot.caption = element_text(hjust = 0)
  )

write_rds(plot1, "Graphics/plot1.rds")
```

